export const mockProducts = [
  {
    id: "1",
    name: "Brake Pad Set",
    slug: "brake-pad-set",
    description:
      "Premium ceramic brake pads for all vehicle types. Long-lasting performance with low dust emission.",
    price: 45.99,
    originalPrice: 59.99,
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    ],
    category: { id: "1", name: "Brakes" },
    brand: { id: "1", name: "Bosch" },
    inStock: true,
    quantity: 50,
    rating: 4.5,
    reviews: 128,
    isFeatured: true,
  },
  {
    id: "2",
    name: "Oil Filter",
    slug: "oil-filter",
    description: "High-quality oil filter for optimal engine protection.",
    price: 12.99,
    images: [
      "https://images.unsplash.com/photo-1552975383-513c7002d408?w=800&q=80",
    ],
    category: { id: "2", name: "Filters" },
    brand: { id: "2", name: "Fram" },
    inStock: true,
    quantity: 200,
    rating: 4.2,
    reviews: 89,
  },
  {
    id: "3",
    name: "Spark Plug Set",
    slug: "spark-plug-set",
    description: "IRidium spark plugs set of 4",
    price: 24.99,
    images: ["/products/spark-plug.jpg"],
    category: { id: "3", name: "Ignition" },
    brand: { id: "3", name: "NGK" },
    inStock: true,
    quantity: 150,
    rating: 4.7,
    reviews: 256,
    isFeatured: true,
  },
  {
    id: "4",
    name: "Air Filter",
    slug: "air-filter",
    description: "Premium air filter",
    price: 18.99,
    images: ["/products/air-filter.jpg"],
    category: { id: "2", name: "Filters" },
    brand: { id: "2", name: "Fram" },
    inStock: true,
    quantity: 100,
    rating: 4.3,
    reviews: 67,
  },
  {
    id: "5",
    name: "Battery 12V",
    slug: "battery-12v",
    description: "12V car battery",
    price: 129.99,
    images: ["/products/battery.jpg"],
    category: { id: "4", name: "Electrical" },
    brand: { id: "4", name: "ACDelco" },
    inStock: true,
    quantity: 30,
    rating: 4.6,
    reviews: 198,
    isFeatured: true,
  },
  {
    id: "6",
    name: "Tire Pressure Monitor",
    slug: "tire-pressure-monitor",
    description: "Digital tire pressure monitoring system",
    price: 34.99,
    images: ["/products/tpm.jpg"],
    category: { id: "4", name: "Electrical" },
    brand: { id: "5", name: "TPM" },
    inStock: true,
    quantity: 75,
    rating: 4.1,
    reviews: 45,
  },
];

export const mockCategories = [
  { id: "1", name: "Brakes", icon: "disc", count: 120 },
  { id: "2", name: "Filters", icon: "filter", count: 85 },
  { id: "3", name: "Ignition", icon: "zap", count: 64 },
  { id: "4", name: "Electrical", icon: "battery", count: 92 },
  { id: "5", name: "Engine", icon: "settings", count: 156 },
  { id: "6", name: "Suspension", icon: "activity", count: 78 },
];

export const mockBrands = [
  { id: "1", name: "Bosch", logo: "/brands/bosch.png" },
  { id: "2", name: "Fram", logo: "/brands/fram.png" },
  { id: "3", name: "NGK", logo: "/brands/ngk.png" },
  { id: "4", name: "ACDelco", logo: "/brands/acdelco.png" },
];

export const mockOrders = [
  {
    id: "ORD-001",
    items: [{ product: mockProducts[0], quantity: 2 }],
    total: 91.98,
    status: "delivered",
    createdAt: "2026-04-10T10:00:00Z",
  },
  {
    id: "ORD-002",
    items: [{ product: mockProducts[2], quantity: 4 }],
    total: 99.96,
    status: "shipped",
    createdAt: "2026-04-12T14:30:00Z",
  },
  {
    id: "ORD-003",
    items: [{ product: mockProducts[4], quantity: 1 }],
    total: 129.99,
    status: "processing",
    createdAt: "2026-04-15T09:15:00Z",
  },
];

export const mockUsers = [
  {
    id: "1",
    email: "admin@gearbazar.com",
    password: "admin123",
    name: "Admin User",
    role: "admin",
    avatar: null,
  },
  {
    id: "2",
    email: "vendor@gearbazar.com",
    password: "vendor123",
    name: "Test Vendor",
    role: "vendor",
    shopName: "Auto Parts Shop",
    verified: true,
  },
  {
    id: "3",
    email: "user@gearbazar.com",
    password: "user123",
    name: "Test Customer",
    role: "customer",
  },
];

export const mockVendors = [
  {
    id: "1",
    name: "Auto Parts Shop",
    email: "vendor@gearbazar.com",
    phone: "+1234567890",
    verified: true,
    rating: 4.5,
    totalSales: 1250,
    totalProducts: 45,
    joinedAt: "2025-01-15",
  },
  {
    id: "2",
    name: "Gear Masters",
    email: "gearmasters@gearbazar.com",
    phone: "+0987654321",
    verified: true,
    rating: 4.8,
    totalSales: 2890,
    totalProducts: 120,
    joinedAt: "2024-06-20",
  },
];

export const mockAnalytics = {
  totalRevenue: 45892.5,
  totalOrders: 234,
  totalUsers: 1250,
  totalVendors: 45,
  revenueChange: 12.5,
  ordersChange: 8.3,
  revenueData: [
    { month: "Jan", revenue: 12500 },
    { month: "Feb", revenue: 15800 },
    { month: "Mar", revenue: 18200 },
    { month: "Apr", revenue: 21500 },
  ],
  topProducts: mockProducts.slice(0, 5),
  recentOrders: mockOrders.slice(0, 3),
};

export default {
  products: mockProducts,
  categories: mockCategories,
  brands: mockBrands,
  orders: mockOrders,
  users: mockUsers,
  vendors: mockVendors,
  analytics: mockAnalytics,
};
